const db = require('./db');

// Placeholder image URLs for the seed script
const RED_DEAD_IMG = "https://via.placeholder.com/300/FF0000/FFFFFF?text=RedDead";
const REACT_SVG_IMG = "https://via.placeholder.com/300/00D8FF/000000?text=React";
const VITE_SVG_IMG = "https://via.placeholder.com/300/9135FF/FFFFFF?text=Vite";

const initialGames = [
  {
    title: "Black Myth: Wukong",
    game_type: "Base Game",
    price: 4999,
    original_price: 4999,
    image_url: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80",
    description: "An action RPG rooted in Chinese mythology. The story is based on Journey to the West, one of the Four Great Classical Novels of Chinese literature.",
    genres: ["Action", "RPG", "Adventure"],
    events: ["Trending"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: true,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Grand Theft Auto VI",
    game_type: "Base Game",
    price: 7999,
    original_price: 7999,
    image_url: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&w=800&q=80",
    description: "Grand Theft Auto VI heads to the state of Leonida, home to the neon-soaked streets of Vice City and beyond in the biggest, most immersive evolution of the series yet.",
    genres: ["Action", "Adventure", "Open World"],
    events: ["Upcoming"],
    is_upcoming: true,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Cyberpunk 2077: Ultimate Edition",
    game_type: "Base Game",
    price: 2999,
    original_price: 5999,
    image_url: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=800&q=80",
    description: "An open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival.",
    genres: ["RPG", "Action", "Sci-Fi"],
    events: ["Sales", "Discounts"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 50,
  },
  {
    title: "Valorant",
    game_type: "Base Game",
    price: 0,
    original_price: 0,
    image_url: "https://cmsassets.rgpub.io/assets/v3/assets/bltb6530b271fddd0b1/blt39645da85638c4c7/66396e956402ec9473be6097/Valorant_EP8_A3_KeyArt_Web_1920x1080.jpg",
    description: "A free-to-play first-person tactical hero shooter developed and published by Riot Games.",
    genres: ["Shooter", "FPS", "Tactical"],
    events: ["Offers"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: false,
    is_free: true,
    discount_percent: 0,
  },
  {
    title: "Hollow Knight: Silksong",
    game_type: "Base Game",
    price: 2499,
    original_price: 2499,
    image_url: "https://gamingbolt.com/wp-content/uploads/2019/02/hollow-knight-silksong.jpg",
    description: "Play as Hornet, princess-protector of Hallownest, and adventure through a whole new kingdom ruled by silk and song!",
    genres: ["Action", "Adventure", "Indie"],
    events: ["Upcoming"],
    is_upcoming: true,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "The Witcher 3: Wild Hunt",
    game_type: "Base Game",
    price: 1499,
    original_price: 3499,
    image_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    description: "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.",
    genres: ["RPG", "Open World", "Fantasy"],
    events: ["Sales"],
    is_upcoming: false,
    is_trending: false,
    is_new_release: false,
    is_free: false,
    discount_percent: 57,
  },
  {
    title: "Genshin Impact",
    game_type: "Base Game",
    price: 0,
    original_price: 0,
    image_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    description: "Step into Teyvat, a vast world teeming with life and flowing with elemental energy.",
    genres: ["RPG", "Adventure", "Anime"],
    events: ["Offers"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: false,
    is_free: true,
    discount_percent: 0,
  },
  {
    title: "Monster Hunter Wilds",
    game_type: "Base Game",
    price: 5999,
    original_price: 5999,
    image_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
    description: "The next generation in the genre-defining Monster Hunter series. Hunt massive monsters in living, breathing environments.",
    genres: ["Action", "RPG", "Multiplayer"],
    events: ["Upcoming"],
    is_upcoming: true,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Red Dead Redemption 2",
    game_type: "Base Game",
    price: 1999,
    original_price: 4999,
    image_url: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?auto=format&fit=crop&w=800&q=80",
    description: "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.",
    genres: ["Action", "Adventure", "Western"],
    events: ["Sales", "Discounts"],
    is_upcoming: false,
    is_trending: false,
    is_new_release: false,
    is_free: false,
    discount_percent: 60,
  },
  {
    title: "Apex Legends",
    game_type: "Base Game",
    price: 0,
    original_price: 0,
    image_url: "https://media.contentapi.ea.com/content/dam/apex-legends/images/2019/01/apex-featured-image-16x9.jpg.adapt.crop191x100.1200w.jpg",
    description: "Conquer with character in Apex Legends, a free-to-play Hero shooter where legendary characters with powerful abilities team up to battle for fortune & glory.",
    genres: ["Shooter", "Battle Royale", "Action"],
    events: ["Offers"],
    is_upcoming: false,
    is_trending: false,
    is_new_release: false,
    is_free: true,
    discount_percent: 0,
  },
  {
    title: "Warhammer 40,000: Space Marine 2",
    game_type: "Base Game",
    price: 5499,
    original_price: 5499,
    image_url: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=800&q=80",
    description: "Embody the superhuman skill and brutality of a Space Marine, the greatest of the Emperor’s warriors.",
    genres: ["Action", "Shooter", "Sci-Fi"],
    events: ["Trending", "New Release"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: true,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Fable",
    game_type: "Base Game",
    price: 4299,
    original_price: 4299,
    image_url: "https://images.purexbox.com/393278c716189/1280x720.jpg",
    description: "What does it mean to be a Hero? In the upcoming Fable, explorers will find out in a land of wonder and whimsy.",
    genres: ["RPG", "Fantasy", "Adventure"],
    events: ["Upcoming"],
    is_upcoming: true,
    is_trending: false,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Ghost of Tsushima",
    game_type: "Base Game",
    price: 3999,
    original_price: 3999,
    image_url: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80",
    description: "In the late 13th century, the Mongol empire has laid waste to entire nations.",
    genres: ["Action", "Adventure", "Open World"],
    events: ["Trending"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Final Fantasy VII Rebirth",
    game_type: "Base Game",
    price: 4999,
    original_price: 4999,
    image_url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    description: "The journey into the unknown continues as Cloud and his friends escape Midgar.",
    genres: ["RPG", "Action", "Adventure"],
    events: ["Trending"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: true,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Star Wars Outlaws",
    game_type: "Upcoming",
    price: 4999,
    original_price: 4999,
    image_url: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=800&q=80",
    description: "The first-ever open world Star Wars game.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    events: ["Upcoming"],
    is_upcoming: true,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Fortnite",
    game_type: "Base Game",
    price: 0,
    original_price: 0,
    image_url: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/capsule_616x353.jpg",
    description: "Battle. Build. Create. Fortnite is a free, always evolving, multiplayer game.",
    genres: ["Battle Royale", "Action", "Building"],
    events: ["Offers"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: false,
    is_free: true,
    discount_percent: 0,
  },
  {
    title: "Resident Evil Village",
    game_type: "Base Game",
    price: 1499,
    original_price: 2999,
    image_url: "https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?auto=format&fit=crop&w=800&q=80",
    description: "Experience survival horror like never before.",
    genres: ["Horror", "Action"],
    events: ["Sales", "Discounts"],
    is_upcoming: false,
    is_trending: false,
    is_new_release: false,
    is_free: false,
    discount_percent: 50,
  },
  {
    title: "Hades II",
    game_type: "Early Access",
    price: 1899,
    original_price: 1899,
    image_url: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/capsule_616x353.jpg",
    description: "Battle beyond the Underworld in this god-like rogue-like dungeon crawler.",
    genres: ["Roguelike", "Action", "Indie"],
    events: ["Trending"],
    is_upcoming: true,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Counter-Strike 2",
    game_type: "Base Game",
    price: 0,
    original_price: 0,
    image_url: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/730/capsule_616x353.jpg",
    description: "Counter-Strike 2 is the largest technical leap in Counter-Strikes history.",
    genres: ["Shooter", "Action", "FPS"],
    events: ["Offers"],
    is_upcoming: false,
    is_trending: true,
    is_new_release: true,
    is_free: true,
    discount_percent: 0,
  },
  {
    title: "Silent Hill 2",
    game_type: "Upcoming",
    price: 3499,
    original_price: 3499,
    image_url: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=800&q=80",
    description: "Experience a master-class in psychological survival horror.",
    genres: ["Horror", "Action", "Adventure"],
    events: ["Upcoming"],
    is_upcoming: true,
    is_trending: true,
    is_new_release: false,
    is_free: false,
    discount_percent: 0,
  },
  {
    title: "Dark Souls III",
    game_type: "Base Game",
    price: 749,
    original_price: 2999,
    image_url: "https://images.unsplash.com/photo-1580234811497-9df7fd2f357e?auto=format&fit=crop&w=800&q=80",
    description: "As fires fade and the world falls into ruin.",
    genres: ["RPG", "Action", "Souls-like"],
    events: ["Sales", "Discounts"],
    is_upcoming: false,
    is_trending: false,
    is_new_release: false,
    is_free: false,
    discount_percent: 75,
  }
];

// Deduplicate by title to avoid inserting the same game multiple times if it appeared in different frontend lists.
const uniqueGames = Array.from(new Map(initialGames.map(game => [game.title, game])).values());

async function seedDatabase() {
  try {
    console.log('Starting database seeding...');

    // Clear existing games to prevent duplicates on re-run
    await db.query('DELETE FROM games');
    console.log('Cleared existing games.');

    for (const game of uniqueGames) {
      const query = `
        INSERT INTO games (
          title, game_type, price, original_price, discount_percent,
          image_url, description, genres, events,
          is_upcoming, is_trending, is_new_release, is_free
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
        ON CONFLICT (title) DO NOTHING
        RETURNING id;
      `;
      const values = [
        game.title, game.game_type, game.price, game.original_price, game.discount_percent,
        game.image_url, game.description, game.genres, game.events,
        game.is_upcoming, game.is_trending, game.is_new_release, game.is_free
      ];
      await db.query(query, values);
      console.log(`Inserted: ${game.title}`);
    }

    console.log('Database seeding completed successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    // It's important to end the process to close the database connection
    process.exit(0);
  }
}

seedDatabase();